SELECT 
    C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM 
    ITEM_INFO AS P
INNER JOIN 
    ITEM_TREE AS TREE ON P.ITEM_ID = TREE.PARENT_ITEM_ID
INNER JOIN 
    ITEM_INFO AS C ON C.ITEM_ID = TREE.ITEM_ID
WHERE 
    P.RARITY = 'RARE'
ORDER BY 
    C.ITEM_ID DESC;