SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA AS E
INNER JOIN
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM 
        ECOLI_DATA 
     GROUP BY 
        YEAR(DIFFERENTIATION_DATE)) AS M
ON 
    YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    1, 2;